ALTER TYPE article_vertical ADD VALUE IF NOT EXISTS 'regtech';

INSERT INTO regulations (name, icon, description, status, status_color, effective_date, impact, applies_to, key_body, hub_section, active, sort_order)
VALUES
  ('DORA — ICT Risk', 'Cpu', 'Digital Operational Resilience Act — ICT risk management requirements', 'In Force', 'emerald', '17 Jan 2025', 'Financial entities must implement robust ICT risk frameworks, incident reporting, and resilience testing. Third-party ICT providers are now directly supervised.', ARRAY['Banks','Investment Firms','Insurance','Payment Institutions','ICT Providers'], 'CySEC / CBC / EIOPA', 'regtech', true, 1),
  ('DORA — Third-Party Risk', 'Server', 'ICT third-party risk management & contractual requirements', 'In Force', 'emerald', '17 Jul 2025', 'Mandatory contractual provisions for all ICT third-party arrangements. Critical providers subject to EU-level oversight framework.', ARRAY['Financial Entities','Cloud Providers','Data Analytics Vendors','SaaS Platforms'], 'ESAs Joint Committee', 'regtech', true, 2),
  ('MiCA — Tech Compliance', 'Shield', 'Markets in Crypto-Assets — technology & infrastructure requirements', 'In Force', 'emerald', '30 Dec 2024', 'CASPs must implement white papers, custody technology, and transaction monitoring systems. CySEC is primary supervisor for Cyprus-licensed entities.', ARRAY['CASPs','E-money Token Issuers','ART Issuers','Crypto Exchanges'], 'CySEC', 'regtech', true, 3),
  ('NIS2 — Cyber Resilience', 'Lock', 'Network & Information Systems Directive 2 — cybersecurity obligations', 'Upcoming', 'amber', 'Q4 2026', 'Expanded scope covers financial services, digital infrastructure, and managed service providers. Incident reporting within 24 hours mandatory.', ARRAY['Essential Entities','Important Entities','MSPs','DNS Providers'], 'DSA / NCA Cyprus', 'regtech', true, 4),
  ('PSD2 / Open Banking', 'Globe', 'Payment Services Directive 2 — API & data access standards', 'In Force', 'emerald', 'Active', 'Strong Customer Authentication (SCA) and open banking APIs are mandatory. TPPs must be registered with CBC for account information services.', ARRAY['Banks','Payment Institutions','TPPs','AISPs','PISPs'], 'Central Bank of Cyprus', 'regtech', true, 5),
  ('AML 6th Directive', 'FileText', '6AMLD — enhanced transaction monitoring & reporting obligations', 'In Force', 'emerald', 'Active', 'Expands predicate offences to 22 categories including cyber crime. Stricter requirements for transaction monitoring systems and beneficial ownership registers.', ARRAY['Credit Institutions','Investment Firms','EMIs','CASPs','Law Firms'], 'MOKAS / CySEC', 'regtech', true, 6)
ON CONFLICT DO NOTHING;