UPDATE directory_companies SET activity_description = t.en
FROM (VALUES
('Αρτοποιία· παραγωγή νωπών ειδών ζαχαροπλαστικής', 'Manufacture of bread; manufacture of fresh pastry goods and cakes'),
('Δραστηριότητες λογιστικής, τήρησης βιβλίων και λογιστικού ελέγχου · παροχή φορολογικών συμβουλών', 'Accounting, bookkeeping and auditing activities; tax consultancy'),
('Κατασκευή άλλων προϊόντων από ξύλο· κατασκευή ειδών από φελλό και ειδών καλαθοποιίας και σπαρτοπλεκτικής', 'Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials'),
('Κατασκευή αμαξωμάτων για μηχανοκίνητα οχήματα · κατασκευή ρυμουλκούμενων και ημιρυμουλκούμενων οχημάτων', 'Manufacture of bodies for motor vehicles; manufacture of trailers and semi-trailers'),
('Κατασκευή επισώτρων (ελαστικά οχημάτων) και σωλήνων από καουτσούκ· αναγόμωση και ανακατασκευή επισώτρων (ελαστικά οχημάτων) από καουτσούκ', 'Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres'),
('Κατεργασία και δέψη δέρματος· κατεργασία και βαφή γουναρικών', 'Tanning and dressing of leather; dressing and dyeing of fur'),
('Λειτουργία φρεάτων παραγωγής αμμοχάλικου και άμμου· εξόρυξη αργίλου και καολίνης', 'Operation of gravel and sand pits; mining of clays and kaolin'),
('Λιανικό εμπόριο άλλων τροφίμων σε ειδικευμένα καταστήματα', 'Retail sale of other food in specialised stores'),
('Λιανικό εμπόριο από επιχειρήσεις πωλήσεων με αλληλογραφία ή μέσω διαδικτύου', 'Retail sale via mail order houses or via Internet'),
('Λιανικό εμπόριο βιβλίων σε ειδικευμένα καταστήματα', 'Retail sale of books in specialised stores'),
('Λιανικό εμπόριο εγγραφών μουσικής και εικόνας σε ειδικευμένα καταστήματα', 'Retail sale of music and video recordings in specialised stores'),
('Οργάνωση συνεδρίων και εμπορικών εκθέσεων', 'Organisation of conventions and trade shows'),
('Παραγωγή άλλων ειδών διατροφής π.δ.κ.α.', 'Manufacture of other food products n.e.c.'),
('Παραγωγή άλλων οργανικών βασικών χημικών ουσιών', 'Manufacture of other organic basic chemicals'),
('Παραγωγή αλουμινίου (αργιλίου)', 'Aluminium production'),
('Παραγωγή αναψυκτικών· παραγωγή μεταλλικού νερού και άλλων εμφιαλωμένων νερών', 'Manufacture of soft drinks; production of mineral waters and other bottled waters'),
('Παραγωγή αρτυμάτων και καρυκευμάτων', 'Manufacture of condiments and seasonings'),
('Παραγωγή αρωμάτων και παρασκευασμάτων καλλωπισμού', 'Manufacture of perfumes and toilet preparations'),
('Παραγωγή ασβέστη και γύψου', 'Manufacture of lime and plaster'),
('Παραγωγή βασικών φαρμακευτικών προϊόντων', 'Manufacture of basic pharmaceutical products'),
('Παραγωγή διαφόρων τύπων κόλλας', 'Manufacture of glues'),
('Παραγωγή έτοιμων γευμάτων και φαγητών', 'Manufacture of prepared meals and dishes'),
('Παραγωγή ζάχαρης', 'Manufacture of sugar'),
('Παραγωγή κακάου, σοκολάτας και ζαχαρωτών', 'Manufacture of cocoa, chocolate and sugar confectionery'),
('Παραγωγή οίνου από σταφύλια', 'Manufacture of wine from grape'),
('Παραγωγή παξιμαδιών και μπισκότων· παραγωγή διατηρούμενων ειδών ζαχαροπλαστικής', 'Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes'),
('Παραγωγή παρασκευασμένων ζωοτροφών για ζώα που εκτρέφονται σε αγροκτήματα', 'Manufacture of prepared feeds for farm animals'),
('Παραγωγή παρασκευασμένων ζωοτροφών για ζώα συντροφιάς', 'Manufacture of prepared pet food'),
('Παραγωγή προϊόντων αλευρόμυλων', 'Manufacture of grain mill products'),
('Παραγωγή προϊόντων διύλισης πετρελαίου', 'Manufacture of refined petroleum products'),
('Παραγωγή σαπουνιών και απορρυπαντικών, προϊόντων καθαρισμού και στίλβωσης', 'Manufacture of soap and detergents, cleaning and polishing preparations'),
('Παραγωγή χαλκού', 'Copper production'),
('Παραγωγή χρωμάτων, βερνικιών και παρόμοιων επιχρισμάτων, μελανιών τυπογραφίας και μαστιχών', 'Manufacture of paints, varnishes and similar coatings, printing ink and mastics'),
('Παραγωγή χρωστικών υλών', 'Manufacture of dyes and pigments'),
('Παραγωγή χυμών φρούτων και λαχανικών', 'Manufacture of fruit and vegetable juice'),
('Παρουσίαση στα μέσα ενημέρωσης', 'Media representation'),
('Πολιτιστική εκπαίδευση', 'Cultural education'),
('Πολλαπλασιασμός των φυτών', 'Plant propagation'),
('Προετοιμασία εργοταξίου', 'Site preparation'),
('Πρωτοβάθμια εκπαίδευση', 'Primary education'),
('Σφαγεία', 'Processing and preserving of meat'),
('Τριτοβάθμια εκπαίδευση', 'Higher education'),
('Υπηρεσίες ασφαλιστικών πρακτόρων και μεσιτών', 'Activities of insurance agents and brokers'),
('Υπηρεσίες μεσιτικών γραφείων', 'Real estate agencies'),
('Υπηρεσίες προεκτύπωσης και προεγγραφής μέσων', 'Pre-press and pre-media services'),
('Χονδρικό εμπόριο ακατέργαστων δερμάτων και δέρματος', 'Wholesale of hides, skins and leather'),
('Χονδρικό εμπόριο αποβλήτων και υπολειμμάτων', 'Wholesale of waste and scrap'),
('Χονδρικό εμπόριο ξυλείας, οικοδομικών υλικών και ειδών υγιεινής', 'Wholesale of wood, construction materials and sanitary equipment'),
('Χονδρικό εμπόριο ρολογιών και κοσμημάτων', 'Wholesale of watches and jewellery'),
('Χονδρικό εμπόριο τηλεπικοινωνιακού εξοπλισμού', 'Wholesale of telecommunications equipment'),
('Χονδρικό εμπόριο χημικών προϊόντων', 'Wholesale of chemical products'),
('Χύτευση σιδήρου', 'Casting of iron'),
('Ψηφιακή εκτύπωση', 'Digital printing')
) AS t(el, en)
WHERE directory_companies.activity_description = t.el;