UPDATE directory_companies SET activity_description = t.en
FROM (VALUES
('Αναπαραγωγή φωτοτυπιών, προετοιμασία εγγράφων και άλλες ειδικευμένες δραστηριότητες γραμματειακής υποστήριξης', 'Photocopying, document preparation and other specialised office support activities'),
('Αντασφάλιση', 'Reinsurance'),
('Αξιολόγηση κινδύνων και ζημιών', 'Risk and damage evaluation'),
('Απόσταξη, ανακαθαρισμός και ανάμιξη αλκοολούχων ποτών', 'Distilling, rectifying and blending of spirits'),
('Αποσυναρμολόγηση παλαιών ειδών', 'Dismantling of wrecks'),
('Αρτοποιία· παραγωγή νωπών ειδών ζαχαροπλαστικής', 'Manufacture of bread; manufacture of fresh pastry goods and cakes'),
('Αστικές και προαστιακές χερσαίες μεταφορές επιβατών', 'Urban and suburban passenger land transport'),
('Ασύρματες τηλεπικοινωνιακές δραστηριότητες', 'Wireless telecommunications activities'),
('Ασφάλειες εκτός από τις ασφάλειες ζωής', 'Non-life insurance'),
('Βιβλιοδετικές και συναφείς δραστηριότητες', 'Bookbinding and related services'),
('Γενικές δραστηριότητες δημόσιας διοίκησης', 'General public administration activities'),
('Γενική δευτεροβάθμια εκπαίδευση', 'General secondary education'),
('Γενικός καθαρισμός κτιρίων', 'General cleaning of buildings'),
('Διακίνηση φορτίων', 'Cargo handling'),
('Διαφημιστικά γραφεία', 'Advertising agencies'),
('Διαχείριση ακίνητης περιουσίας, έναντι αμοιβής ή βάσει σύμβασης', 'Real estate management on a fee or contract basis'),
('Δικτυακές πύλες', 'Web portals'),
('Δοκιμαστικές γεωτρήσεις', 'Test drilling and boring'),
('Δορυφορικές τηλεπικοινωνιακές δραστηριότητες', 'Satellite telecommunications activities'),
('Δραστηριότητες αθλητικών ομίλων', 'Activities of sports clubs'),
('Δραστηριότητες άλλων οργανώσεων π.δ.κ.α.', 'Activities of other membership organisations n.e.c.'),
('Δραστηριότητες αποκλειστικού(-ής) νοσοκόμου κατ'' οίκον', 'Home nursing activities'),
('Δραστηριότητες αποκλειστικού(-ής) νοσοκόμου κατ'' οίκον για ηλικιωμένους και άτομα με αναπηρία', 'Home nursing activities for the elderly and disabled'),
('Δραστηριότητες αρχιτεκτόνων', 'Architectural activities'),
('Δραστηριότητες άσκησης γενικών ιατρικών επαγγελμάτων', 'General medical practice activities'),
('Δραστηριότητες άσκησης ειδικών ιατρικών επαγγελμάτων', 'Specialist medical practice activities'),
('Δραστηριότητες άσκησης οδοντιατρικών επαγγελμάτων', 'Dental practice activities'),
('Δραστηριότητες βιβλιοθηκών και αρχειοφυλακείων', 'Library and archive activities'),
('Δραστηριότητες βοτανικών και ζωολογικών κήπων και φυσικών βιοτόπων', 'Botanical and zoological gardens and nature reserve activities'),
('Δραστηριότητες βρεφονηπιακών και παιδικών σταθμών', 'Child day-care activities'),
('Δραστηριότητες γραφείων είσπραξης και γραφείων οικονομικών και εμπορικών πληροφοριών', 'Activities of collection agencies and credit bureaus'),
('Δραστηριότητες γραφείων ευρέσεως εργασίας', 'Activities of employment placement agencies'),
('Δραστηριότητες γραφείων ευρέσεως προσωρινής εργασίας', 'Temporary employment agency activities'),
('Δραστηριότητες γραφείων κηδειών και συναφείς δραστηριότητες', 'Funeral and related activities'),
('Δραστηριότητες γραφείων οργανωμένων ταξιδιών', 'Tour operator activities'),
('Δραστηριότητες δημοσίων σχέσεων και επικοινωνίας', 'Public relations and communication activities'),
('Δραστηριότητες διανομής κινηματογραφικών ταινιών, βίντεο και τηλεοπτικών προγραμμάτων', 'Motion picture, video and television programme distribution activities'),
('Δραστηριότητες διαχείρισης κεφαλαίων', 'Fund management activities'),
('Δραστηριότητες ειδικευμένου σχεδίου', 'Specialised design activities'),
('Δραστηριότητες εξυγίανσης και άλλες υπηρεσίες για τη διαχείριση αποβλήτων', 'Remediation activities and other waste management services'),
('Δραστηριότητες επαγγελματικών οργανώσεων', 'Activities of professional membership organisations'),
('Δραστηριότητες επιχειρηματικών και εργοδοτικών οργανώσεων', 'Activities of business and employers membership organisations'),
('Δραστηριότητες έρευνας', 'Investigation activities'),
('Δραστηριότητες θρησκευτικών οργανώσεων', 'Activities of religious organisations'),
('Δραστηριότητες κατασκευής στεγών', 'Roofing activities'),
('Δραστηριότητες κεντρικών γραφείων', 'Activities of head offices'),
('Δραστηριότητες κοινωνικής μέριμνας χωρίς παροχή καταλύματος για ηλικιωμένους και άτομα με αναπηρία', 'Social work activities without accommodation for the elderly and disabled'),
('Δραστηριότητες κομμωτηρίων, κουρείων και κέντρων αισθητικής', 'Hairdressing and other beauty treatment'),
('Δραστηριότητες λογιστικής, τήρησης βιβλίων και λογιστικού ελέγχου · παροχή φορολογικών συμβουλών', 'Accounting, bookkeeping and auditing activities; tax consultancy'),
('Δραστηριότητες μετά τη συγκομιδή', 'Post-harvest crop activities'),
('Δραστηριότητες μετάφρασης και διερμηνείας', 'Translation and interpretation activities'),
('Δραστηριότητες μηχανικών και συναφείς δραστηριότητες παροχής τεχνικών συμβουλών', 'Engineering activities and related technical consultancy'),
('Δραστηριότητες παραγωγής κινηματογραφικών ταινιών, βίντεο και τηλεοπτικών προγραμμάτων', 'Motion picture, video and television programme production activities'),
('Δραστηριότητες πάρκων αναψυχής και άλλων θεματικών πάρκων', 'Activities of amusement parks and theme parks'),
('Δραστηριότητες παροχής επιχειρηματικών συμβουλών και άλλων συμβουλών διαχείρισης', 'Management consultancy activities'),
('Δραστηριότητες παροχής ιδιωτικής προστασίας', 'Private security activities'),
('Δραστηριότητες παροχής ποτών', 'Beverage serving activities'),
('Δραστηριότητες παροχής συμβουλών σχετικά με τους ηλεκτρονικούς υπολογιστές', 'Computer consultancy activities'),
('Δραστηριότητες πρακτορείων ειδήσεων', 'News agency activities'),
('Δραστηριότητες προβολής κινηματογραφικών ταινιών', 'Motion picture projection activities'),
('Δραστηριότητες προγραμματισμού ηλεκτρονικών συστημάτων', 'Computer programming activities'),
('Δραστηριότητες συναφείς με τις αεροπορικές μεταφορές', 'Service activities incidental to air transportation'),
('Δραστηριότητες συναφείς με τις πλωτές μεταφορές', 'Service activities incidental to water transportation'),
('Δραστηριότητες συναφείς με τις χερσαίες μεταφορές', 'Service activities incidental to land transportation'),
('Δραστηριότητες συνδυασμού βοηθητικών υπηρεσιών', 'Combined facilities support activities'),
('Δραστηριότητες συνοδευτικές της παραγωηής κινηματογραφικών ταινιών, βίντεο και τηλεοπτικών προγραμμάτων', 'Motion picture, video and television programme post-production activities'),
('Δραστηριότητες συσκευασίας', 'Packaging activities'),
('Δραστηριότητες σχετικά με συναλλαγές συμβάσεων χρεογράφων και αγαθών', 'Activities of security and commodity contracts dealing'),
('Δραστηριότητες σχετικές με τη φυσική ευεξία', 'Physical well-being activities'),
('Δραστηριότητες σχολών οδηγών', 'Driving school activities'),
('Δραστηριότητες ταξιδιωτικών πρακτορείων', 'Travel agency activities'),
('Δραστηριότητες τηλεφωνικών κέντρων', 'Call centre activities'),
('Δραστηριότητες υπηρεσιών εστιατορίων και κινητών μονάδων εστίασης', 'Restaurants and mobile food service activities'),
('Δραστηριότητες υπηρεσιών τοπίου', 'Landscape service activities'),
('Δραστηριότητες υπηρεσιών τροφοδοσίας για εκδηλώσεις', 'Event catering activities'),
('Εγκαταστάσεις γυμναστικής', 'Fitness facilities'),
('Έκδοση άλλου λογισμικού', 'Other software publishing'),
('Έκδοση βιβλίων', 'Book publishing'),
('Έκδοση εφημερίδων', 'Publishing of newspapers'),
('Έκδοση παιχνιδιών για ηλεκτρονικούς υπολογιστές', 'Publishing of computer games'),
('Έκδοση περιοδικών κάθε είδους', 'Publishing of journals and periodicals'),
('Έκδοση τηλεφωνικών και κάθε είδους καταλόγων', 'Publishing of directories and mailing lists'),
('Εκμετάλλευση αθλητικών εγκαταστάσεων', 'Operation of sports facilities'),
('Εκμετάλλευση αιθουσών θεαμάτων και συναφείς δραστηριότητες', 'Operation of arts facilities'),
('Εκμετάλλευση ταξί', 'Taxi operation'),
('Εκμίσθωση και διαχείριση ιδιόκτητων ή μισθωμένων ακινήτων', 'Renting and operating of own or leased real estate'),
('Εκμίσθωση πνευματικής ιδιοκτησίας και παρεμφερών προϊόντων, με εξαίρεση τα έργα με δικαιώματα πνευματικής ιδιοκτησίας', 'Leasing of intellectual property and similar products, except copyrighted works'),
('Εκπαιδευτικές υποστηρικτικές δραστηριότητες', 'Educational support activities'),
('Εκτροφή αιγοπροβάτων', 'Raising of sheep and goats'),
('Εκτροφή άλλων βοοειδών και βουβαλιών', 'Raising of other cattle and buffaloes'),
('Εκτροφή άλλων ζώων', 'Raising of other animals'),
('Εκτροφή αλόγων και άλλων ιπποειδών', 'Raising of horses and other equines'),
('Εκτροφή βοοειδών γαλακτοπαραγωγής', 'Raising of dairy cattle'),
('Εκτροφή πουλερικών', 'Raising of poultry'),
('Εκτροφή χοίρων', 'Raising of swine/pigs'),
('Εμπορικοί αντιπρόσωποι ειδικευμένοι στην πώληση άλλων συγκεκριμένων προϊόντων', 'Agents specialised in the sale of other particular products'),
('Εμπορικοί αντιπρόσωποι που μεσολαβούν στην πώληση γεωργικών πρώτων υλών, ζώντων ζώων, κλωστοϋφαντουργικών πρώτων υλών και ημιτελών προϊόντων', 'Agents involved in the sale of agricultural raw materials, live animals, textile raw materials and semi-finished goods'),
('Εμπορικοί αντιπρόσωποι που μεσολαβούν στην πώληση διαφόρων ειδών', 'Agents involved in the sale of a variety of goods'),
('Εμπορικοί αντιπρόσωποι που μεσολαβούν στην πώληση επίπλων, ειδών οικιακής χρήσης, σιδηρικών και ειδών κιγκαλερίας', 'Agents involved in the sale of furniture, household goods, hardware and ironmongery'),
('Εμπορικοί αντιπρόσωποι που μεσολαβούν στην πώληση κλωστοϋφαντουργικών προϊόντων, ενδυμάτων, γουναρικών, υποδημάτων και δερμάτινων προϊόντων', 'Agents involved in the sale of textiles, clothing, fur, footwear and leather goods'),
('Ηχογραφήσεις και μουσικές εκδόσεις', 'Sound recording and music publishing activities'),
('Θαλάσσια αλιεία', 'Marine fishing'),
('Θαλάσσια υδατοκαλλιέργεια', 'Marine aquaculture'),
('Καλλιέργεια άλλων μη πολυετών φυτών', 'Growing of other non-perennial crops'),
('Καλλιέργεια ελαιωδών καρπών', 'Growing of oleaginous fruits'),
('Καλλιέργεια καρυκευτικών, αρωματικών, θεραπευτικών και φαρμακευτικών φυτών', 'Growing of spice, aromatic, drug and pharmaceutical crops'),
('Καλλιέργεια μηλοειδών και πυρηνόκαρπων', 'Growing of pome fruits and stone fruits'),
('Καλλιέργεια σταφυλιών', 'Growing of grapes'),
('Καλλιτεχνική δημιουργία', 'Artistic creation'),
('Καταλύματα διακοπών και άλλα καταλύματα σύντομης διαμονής', 'Holiday and other short-stay accommodation'),
('Καταπιστεύματα, κεφάλαια και παρεμφερή χρηματοπιστωτικά μέσα', 'Trusts, funds and similar financial entities'),
('Κατασκευή αεροσκαφών και διαστημοπλοίων και συναφών μηχανημάτων', 'Manufacture of air and spacecraft and related machinery'),
('Κατασκευή άλλων ειδών από χαρτί και χαρτόνι', 'Manufacture of other articles of paper and paperboard'),
('Κατασκευή άλλων ενδυμάτων και εξαρτημάτων ένδυσης', 'Manufacture of other wearing apparel and accessories'),
('Κατασκευή άλλων εξωτερικών ενδυμάτων', 'Manufacture of other outerwear'),
('Κατασκευή άλλων επίπλων', 'Manufacture of other furniture'),
('Κατασκευή άλλων εργαλειομηχανών', 'Manufacture of other machine tools'),
('Κατασκευή άλλων έργων πολιτικού μηχανικού π.δ.κ.α.', 'Construction of other civil engineering projects n.e.c.'),
('Κατασκευή άλλων ηλεκτρονικών και ηλεκτρικών συρμάτων και καλωδίων', 'Manufacture of other electronic and electric wires and cables'),
('Κατασκευή άλλων μερών και εξαρτημάτων για μηχανοκίνητα οχήματα', 'Manufacture of other parts and accessories for motor vehicles'),
('Κατασκευή άλλων μεταλλικών ντεποζίτων, δεξαμενών και δοχείων', 'Manufacture of other tanks, reservoirs and containers of metal'),
('Κατασκευή άλλων μεταλλικών προϊόντων π.δ.κ.α.', 'Manufacture of other fabricated metal products n.e.c.'),
('Κατασκευή άλλων μηχανημάτων γενικής χρήσης π.δ.κ.α.', 'Manufacture of other general-purpose machinery n.e.c.'),
('Κατασκευή άλλων μηχανημάτων ειδικής χρήσης π.δ.κ.α.', 'Manufacture of other special-purpose machinery n.e.c.'),
('Κατασκευή άλλων ξυλουργικών προϊόντων οικοδομικής', 'Manufacture of other builders'' carpentry and joinery'),
('Κατασκευή άλλων πλεκτών ειδών και ειδών πλέξης κροσέ', 'Manufacture of other knitted and crocheted apparel'),
('Κατασκευή άλλων προϊόντων από ελαστικό (καουτσούκ)', 'Manufacture of other rubber products'),
('Κατασκευή άλλων προϊόντων από ξύλο· κατασκευή ειδών από φελλό και ειδών καλαθοποιίας και σπαρτοπλεκτικής', 'Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials'),
('Κατασκευή άλλων προϊόντων από σκυρόδεμα, γύψο και τσιμέντο', 'Manufacture of other articles of concrete, plaster and cement'),
('Κατασκευή άλλων υφαντουργικών προϊόντων π.δ.κ.α.', 'Manufacture of other textiles n.e.c.'),
('Κατασκευή αμαξωμάτων για μηχανοκίνητα οχήματα · κατασκευή ρυμουλκούμενων και ημιρυμουλκούμενων οχημάτων', 'Manufacture of bodies for motor vehicles; manufacture of trailers and semi-trailers'),
('Κατασκευή αντικολλητών (κόντρα-πλακέ) και άλλων πλακών με βάση το ξύλο', 'Manufacture of veneer sheets and wood-based panels'),
('Κατασκευή δερμάτινων ενδυμάτων', 'Manufacture of articles of fur'),
('Κατασκευή δομικών προϊόντων από γύψο', 'Manufacture of plaster products for construction purposes'),
('Κατασκευή δομικών προϊόντων από σκυρόδεμα', 'Manufacture of concrete products for construction purposes'),
('Κατασκευή δρόμων και αυτοκινητοδρόμων', 'Construction of roads and motorways'),
('Κατασκευή ειδών από σύρμα, αλυσίδων και ελατηρίων', 'Manufacture of wire products, chain and springs'),
('Κατασκευή ειδών οικιακής χρήσης, ειδών υγιεινής και ειδών τουαλέτας', 'Manufacture of household and sanitary goods and of toilet requisites'),
('Κατασκευή ειδών χαρτοπωλείου (χαρτικά)', 'Manufacture of stationery'),
('Κατασκευή ενδυμάτων εργασίας', 'Manufacture of workwear'),
('Κατασκευή εξαρτημάτων καλωδίωσης', 'Manufacture of wiring devices'),
('Κατασκευή εξοπλισμού ανύψωσης και διακίνησης φορτίων', 'Manufacture of lifting and handling equipment'),
('Κατασκευή εξοπλισμού επικοινωνίας', 'Manufacture of communication equipment'),
('Κατασκευή εξοπλισμού υδραυλικής ενέργειας', 'Manufacture of fluid power equipment'),
('Κατασκευή επίπεδου γυαλιού', 'Manufacture of flat glass'),
('Κατασκευή επίπλων κουζίνας', 'Manufacture of kitchen furniture'),
('Κατασκευή επισώτρων (ελαστικά οχημάτων) και σωλήνων από καουτσούκ· αναγόμωση και ανακατασκευή επισώτρων (ελαστικά οχημάτων) από καουτσούκ', 'Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres'),
('Κατασκευή εργαλείων', 'Manufacture of tools'),
('Κατασκευή εσωρούχων', 'Manufacture of underwear'),
('Κατασκευή έτοιμου σκυροδέματος', 'Manufacture of ready-mixed concrete'),
('Κατασκευή έτοιμων κλωστοϋφαντουργικών ειδών, εκτός από ενδύματα', 'Manufacture of made-up textile articles, except apparel'),
('Κατασκευή ηλεκτροκινητήρων, ηλεκτρογεννητριών και ηλεκτρικών μετασχηματιστών', 'Manufacture of electric motors, generators and transformers'),
('Κατασκευή ηλεκτρολογικού φωτιστικού εξοπλισμού', 'Manufacture of electric lighting equipment'),
('Κατασκευή ιατρικών και οδοντιατρικών οργάνων και προμηθειών', 'Manufacture of medical and dental instruments and supplies'),
('Κατασκευή ινών γυαλιού', 'Manufacture of glass fibres'),
('Κατασκευή και κατεργασία άλλων ειδών γυαλιού, περιλαμβανομένου του γυαλιού για τεχνικές χρήσεις', 'Manufacture and processing of other glass, including technical glassware'),
('Κατασκευή κεραμικών ειδών οικιακής χρήσης και κεραμικών διακοσμητικών ειδών', 'Manufacture of ceramic household and ornamental articles'),
('Κατασκευή κλειδαριών και μεντεσέδων', 'Manufacture of locks and hinges'),
('Κατασκευή κοινωφελών έργων ηλεκτρικού ρεύματος και τηλεπικοινωνιών', 'Construction of utility projects for electricity and telecommunications'),
('Κατασκευή κοινωφελών έργων σχετικών με υγρά', 'Construction of utility projects for fluids'),
('Κατασκευή κονιαμάτων', 'Manufacture of mortars'),
('Κατασκευή κοσμημάτων απομίμησης και συναφών ειδών', 'Manufacture of imitation jewellery and related articles'),
('Κατασκευή κοσμημάτων και συναφών ειδών', 'Manufacture of jewellery and related articles'),
('Κατασκευή κτιρίων για κατοικίες και μη', 'Construction of residential and non-residential buildings'),
('Κατασκευή κυματοειδούς χαρτιού και χαρτονιού και εμπορευματοκιβωτίων από χαρτί και χαρτόνι', 'Manufacture of corrugated paper and paperboard and of containers of paper and paperboard'),
('Κατασκευή μεταλλικών πορτών και παραθύρων', 'Manufacture of metal doors and windows'),
('Κατασκευή μη ηλεκτρικών οικιακών συσκευών', 'Manufacture of non-electric domestic appliances'),
('Κατασκευή μηχανημάτων επεξεργασίας τροφίμων, ποτών και καπνού', 'Manufacture of machinery for food, beverage and tobacco processing'),
('Κατασκευή μηχανημάτων παραγωγής πλαστικών και ελαστικών ειδών', 'Manufacture of plastics and rubber production machinery'),
('Κατασκευή μηχανοκίνητων οχημάτων', 'Manufacture of motor vehicles'),
('Κατασκευή ξύλινων εμπορευματοκιβωτίων', 'Manufacture of wooden containers'),
('Κατασκευή όπλων και πυρομαχικών', 'Manufacture of weapons and ammunition'),
('Κατασκευή πλαστικών ειδών συσκευασίας', 'Manufacture of plastics packing goods'),
('Κατασκευή πλαστικών οικοδομικών υλικών', 'Manufacture of builders'' ware of plastic'),
('Κατασκευή πλαστικών πλακών, φύλλων, σωλήνων και ειδών καθορισμένης μορφής', 'Manufacture of plastic plates, sheets, tubes and profiles'),
('Κατασκευή σκουπών και βουρτσών', 'Manufacture of brooms and brushes'),
('Κατασκευή συσκευών διανομής και ελέγχου ηλεκτρικού ρεύματος', 'Manufacture of electricity distribution and control apparatus'),
('Κατασκευή τούβλων, πλακιδίων και λοιπών δομικών προϊόντων από οπτή γη', 'Manufacture of bricks, tiles and construction products in baked clay'),
('Κατασκευή υδραυλικών και λιμενικών έργων', 'Construction of water projects'),
('Κατασκευή υποδημάτων', 'Manufacture of footwear'),
('Κατασκευή φούρνων, κλιβάνων και καυστήρων', 'Manufacture of ovens, furnaces and furnace burners'),
('Κατασκευή χαλύβδινων σωλήνων, αγωγών, κοίλων ειδών με καθορισμένη μορφή και συναφών εξαρτημάτων', 'Manufacture of steel tubes, pipes, hollow profiles and related fittings'),
('Κατασκευή χαρτιού και χαρτονιού', 'Manufacture of paper and paperboard'),
('Κατασκευή ψυκτικού και κλιματιστικού εξοπλισμού μη οικιακής χρήσης', 'Manufacture of non-domestic cooling and ventilation equipment'),
('Κατεργασία και δέψη δέρματος· κατεργασία και βαφή γουναρικών', 'Tanning and dressing of leather; dressing and dyeing of fur'),
('Κατεργασία και επικάλυψη μετάλλων', 'Treatment and coating of metals'),
('Κοπή, μορφοποίηση και τελική επεξεργασία λίθων', 'Cutting, shaping and finishing of stone'),
('Κτηνιατρικές δραστηριότητες', 'Veterinary activities'),
('Λειτουργία γαλακτοκομείων και τυροκομία', 'Operation of dairies and cheese making'),
('Λειτουργία φρεάτων παραγωγής αμμοχάλικου και άμμου· εξόρυξη αργίλου και καολίνης', 'Operation of gravel and sand pits; mining of clays and kaolin'),
('Λιανικό εμπόριο αθλητικού εξοπλισμού σε ειδικευμένα καταστήματα', 'Retail sale of sporting equipment in specialised stores'),
('Λιανικό εμπόριο αλλού μη ταξινομημένων νέων ειδών, σε ειδικευμένα καταστήματα', 'Retail sale of other new goods in specialised stores'),
('Λιανικό εμπόριο ανθέων, φυτών, σπόρων, λιπασμάτων, ζώων συντροφιάς και τροφών ζώων συντροφιάς, σε ειδικευμένα καταστήματα', 'Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores'),
('Λιανικό εμπόριο αποκλειστικά μέσω αλληλογραφίας ή μέσω Διαδικτύου', 'Retail sale via mail order houses or via Internet'),
('Λιανικό εμπόριο αρτοποιείου και ζαχαροπλαστικής', 'Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores'),
('Λιανικό εμπόριο βιβλίων, σε ειδικευμένα καταστήματα', 'Retail sale of books in specialised stores'),
('Λιανικό εμπόριο εφημερίδων και γραφικής ύλης, σε ειδικευμένα καταστήματα', 'Retail sale of newspapers and stationery in specialised stores'),
('Λιανικό εμπόριο ηλεκτρικών οικιακών συσκευών σε ειδικευμένα καταστήματα', 'Retail sale of electrical household appliances in specialised stores'),
('Λιανικό εμπόριο ηλεκτρονικών υπολογιστών, περιφερειακών μονάδων ηλεκτρονικών υπολογιστών και λογισμικού σε ειδικευμένα καταστήματα', 'Retail sale of computers, computer peripheral units and software in specialised stores'),
('Λιανικό εμπόριο καλλυντικών και ειδών τουαλέτας σε ειδικευμένα καταστήματα', 'Retail sale of cosmetic and toilet articles in specialised stores'),
('Λιανικό εμπόριο μεταχειρισμένων ειδών σε καταστήματα', 'Retail sale of second-hand goods in stores'),
('Λιανικό εμπόριο οπωρολαχανικών (φρούτων και λαχανικών) σε ειδικευμένα καταστήματα', 'Retail sale of fruit and vegetables in specialised stores'),
('Λιανικό εμπόριο ποτών σε ειδικευμένα καταστήματα', 'Retail sale of beverages in specialised stores'),
('Λιανικό εμπόριο προϊόντων κρέατος και αλλαντικών σε ειδικευμένα καταστήματα', 'Retail sale of meat and meat products in specialised stores'),
('Λιανικό εμπόριο ρολογιών και κοσμημάτων σε ειδικευμένα καταστήματα', 'Retail sale of watches and jewellery in specialised stores'),
('Λιανικό εμπόριο σε πάγκους και αγορές', 'Retail sale via stalls and markets'),
('Λιανικό εμπόριο τηλεπικοινωνιακού εξοπλισμού σε ειδικευμένα καταστήματα', 'Retail sale of telecommunications equipment in specialised stores'),
('Λιανικό εμπόριο τροφίμων σε ειδικευμένα καταστήματα', 'Retail sale of food in specialised stores'),
('Λιανικό εμπόριο υλικών χρωματισμού, γυαλιών και εξοπλισμού σε ειδικευμένα καταστήματα', 'Retail sale of hardware, paints and glass in specialised stores'),
('Λιανικό εμπόριο φαρμακευτικών ειδών σε ειδικευμένα καταστήματα', 'Retail sale of pharmaceutical goods in specialised stores'),
('Λοιπά αλλού μη ταξινομημένα ειδικά κατασκευαστικά έργα', 'Other specialised construction activities n.e.c.'),
('Μεικτή γεωργία', 'Mixed farming'),
('Μεταλλουργία χάλυβα', 'Manufacture of basic iron and steel'),
('Μεταποίηση τσαγιού και καφέ', 'Processing of tea and coffee'),
('Μη εξειδικευμένο χονδρικό εμπόριο', 'Non-specialised wholesale trade'),
('Μη εξειδικευμένο χονδρικό εμπόριο τροφίμων, ποτών και καπνού', 'Non-specialised wholesale of food, beverages and tobacco'),
('Νοσοκομειακές δραστηριότητες', 'Hospital activities'),
('Νομικές δραστηριότητες', 'Legal activities'),
('Ξενοδοχεία και παρόμοια καταλύματα', 'Hotels and similar accommodation'),
('Ξυλουργικές εργασίες', 'Joinery installation'),
('Οδικές μεταφορές εμπορευμάτων', 'Freight transport by road'),
('Ολοκληρωμένη διαχείριση εγκαταστάσεων', 'Combined facilities support activities'),
('Παραγωγή ανανεώσιμης ηλεκτρικής ενέργειας', 'Production of electricity from renewable sources'),
('Παραγωγή βιομηχανικών αερίων', 'Manufacture of industrial gases'),
('Παραγωγή εξαρτημάτων ηλεκτρονικών υπολογιστών', 'Manufacture of electronic components'),
('Παραγωγή ζυμαρικών, λαζανιών, κουσκούς και παρομοίων αλευρωδών προϊόντων', 'Manufacture of macaroni, noodles, couscous and similar farinaceous products'),
('Παραγωγή κρέατος πτηνών', 'Production of meat from poultry'),
('Παραγωγή μεταλλικών κατασκευών και μερών κατασκευών', 'Manufacture of metal structures and parts of structures'),
('Παραγωγή παγωτών', 'Manufacture of ice cream'),
('Παραγωγή παρασιτοκτόνων και άλλων αγροχημικών προϊόντων', 'Manufacture of pesticides and other agrochemical products'),
('Παραγωγή προϊόντων κρέατος και κρέατος πουλερικών', 'Processing and preserving of meat and production of meat products'),
('Παραγωγή σαπουνιού και απορρυπαντικών, προϊόντων καθαρισμού και στίλβωσης, αρωμάτων και παρασκευασμάτων καλλωπισμού', 'Manufacture of soap and detergents, cleaning and polishing preparations, perfumes and toilet preparations'),
('Παραγωγή τυριού', 'Manufacture of cheese'),
('Παραγωγή χρωμάτων, βερνικιών και παρόμοιων επιστρωμάτων, μελανιών τυπογραφίας και μαστιχών', 'Manufacture of paints, varnishes and similar coatings, printing ink and mastics'),
('Παροχή άλλων υπηρεσιών πληροφορικής', 'Other information technology service activities'),
('Πλύσιμο και (στεγνό) καθάρισμα κλωστοϋφαντουργικών και γούνινων προϊόντων', 'Washing and (dry-)cleaning of textile and fur products'),
('Ραδιοφωνικές εκπομπές', 'Radio broadcasting'),
('Σιδηροδρομικές μεταφορές εμπορευμάτων', 'Freight rail transport'),
('Συλλογή μη επικίνδυνων απορριμμάτων', 'Collection of non-hazardous waste'),
('Συντήρηση και επισκευή μηχανοκίνητων οχημάτων', 'Maintenance and repair of motor vehicles'),
('Τεχνικές δοκιμές και αναλύσεις', 'Technical testing and analysis'),
('Τηλεοπτικός προγραμματισμός και τηλεοπτικές εκπομπές', 'Television programming and broadcasting activities'),
('Τυπογραφία', 'Printing n.e.c.'),
('Υγρή αλιεία', 'Freshwater fishing'),
('Υπεράκτιες μεταφορές εμπορευμάτων', 'Sea and coastal freight water transport'),
('Υπεράκτιες μεταφορές επιβατών', 'Sea and coastal passenger water transport'),
('Υπηρεσίες εκκαθάρισης και διακανονισμού χρεογράφων', 'Security and commodity exchange activities'),
('Υπηρεσίες προεκτύπωσης και προεγγραφής μέσων', 'Pre-press and pre-media services'),
('Υποδοχή και φιλοξενία επισκεπτών', 'Visitor reception and hosting'),
('Φαρμακευτικά παρασκευάσματα', 'Manufacture of pharmaceutical preparations'),
('Φύλαξη και αποθήκευση', 'Warehousing and storage'),
('Φωτογραφικές δραστηριότητες', 'Photographic activities'),
('Χαρτογραφική και χωρική πληροφόρηση', 'Cartographic and spatial information activities'),
('Χονδρικό εμπόριο αγροτικών μηχανημάτων, εξοπλισμού και προμηθειών', 'Wholesale of agricultural machinery, equipment and supplies'),
('Χονδρικό εμπόριο αλκοολούχων και άλλων ποτών', 'Wholesale of beverages'),
('Χονδρικό εμπόριο άλλων ειδών οικιακής χρήσης', 'Wholesale of other household goods'),
('Χονδρικό εμπόριο άλλων ενδιάμεσων προϊόντων', 'Wholesale of other intermediate products'),
('Χονδρικό εμπόριο άλλων μηχανημάτων και εξοπλισμού', 'Wholesale of other machinery and equipment'),
('Χονδρικό εμπόριο άλλων τροφίμων, στο οποίο περιλαμβάνονται ψάρια, καρκινοειδή και μαλάκια', 'Wholesale of other food, including fish, crustaceans and molluscs'),
('Χονδρικό εμπόριο ανταλλακτικών και εξαρτημάτων μηχανοκίνητων οχημάτων', 'Wholesale of motor vehicle parts and accessories'),
('Χονδρικό εμπόριο γαλακτοκομικών προϊόντων, αβγών και βρώσιμων ελαίων και λιπών', 'Wholesale of dairy products, eggs and edible oils and fats'),
('Χονδρικό εμπόριο δέρματος', 'Wholesale of hides, skins and leather'),
('Χονδρικό εμπόριο ειδών σιδηρικών, υδραυλικών και θέρμανσης και προμηθειών', 'Wholesale of hardware, plumbing and heating equipment and supplies'),
('Χονδρικό εμπόριο ενδυμάτων και υποδημάτων', 'Wholesale of clothing and footwear'),
('Χονδρικό εμπόριο ηλεκτρονικού και τηλεπικοινωνιακού εξοπλισμού και εξαρτημάτων', 'Wholesale of electronic and telecommunications equipment and parts'),
('Χονδρικό εμπόριο ηλεκτρονικών υπολογιστών, περιφερειακού εξοπλισμού ηλεκτρονικών υπολογιστών και λογισμικού', 'Wholesale of computers, computer peripheral equipment and software'),
('Χονδρικό εμπόριο καπνού', 'Wholesale of tobacco products'),
('Χονδρικό εμπόριο κατασκευαστικών υλικών, ειδών υγιεινής και σιδηρικών', 'Wholesale of construction materials, hardware, plumbing and heating equipment'),
('Χονδρικό εμπόριο κρέατος και προϊόντων κρέατος', 'Wholesale of meat and meat products'),
('Χονδρικό εμπόριο μεταλλεύματος και μετάλλων', 'Wholesale of metals and metal ores'),
('Χονδρικό εμπόριο μηχανημάτων γραφείου και εξοπλισμού γραφείων', 'Wholesale of office machinery and equipment'),
('Χονδρικό εμπόριο μηχανοκίνητων οχημάτων', 'Sale of cars and light motor vehicles'),
('Χονδρικό εμπόριο οπωρολαχανικών (φρούτων και λαχανικών)', 'Wholesale of fruit and vegetables'),
('Χονδρικό εμπόριο σάκχαρης, σοκολάτας και ειδών ζαχαροπλαστικής', 'Wholesale of sugar and chocolate and sugar confectionery'),
('Χονδρικό εμπόριο στερεών, υγρών και αερίων καυσίμων και συναφών προϊόντων', 'Wholesale of solid, liquid and gaseous fuels and related products'),
('Χονδρικό εμπόριο φαρμακευτικών προϊόντων', 'Wholesale of pharmaceutical goods'),
('Χονδρικό εμπόριο χημικών προϊόντων', 'Wholesale of chemical products'),
('Χρηματοδοτική μίσθωση (leasing)', 'Financial leasing'),
('Χρηματοοικονομικές υπηρεσίες, εκτός ασφαλιστικών δραστηριοτήτων και δραστηριοτήτων συνταξιοδοτικών ταμείων', 'Other financial service activities, except insurance and pension funding'),
('Χύτευση ελαφρών μετάλλων', 'Casting of light metals'),
('Ψηφιακή εκτύπωση', 'Digital printing')
) AS t(el, en)
WHERE directory_companies.activity_description = t.el;