UPDATE public.directory_companies dc
SET activity_description = t.en
FROM (VALUES
('Αγοραπωλησία ιδιόκτητων ακινήτων', 'Buying and selling of own real estate'),
('Αεροπορικές μεταφορές εμπορευμάτων', 'Air transport of freight'),
('Αεροπορικές μεταφορές επιβατών', 'Air transport of passengers'),
('Αθλητική και ψυχαγωγική εκπαίδευση', 'Sports and recreation education'),
('Άλλα καταλύματα', 'Other accommodation'),
('Άλλες αθλητικές δραστηριότητες', 'Other sports activities'),
('Άλλες δενδρώδεις και θαμνώδεις καλλιέργειες φρούτων και καρπών με κέλυφος', 'Other tree and bush fruit and nut farming'),
('Άλλες δραστηριότητες ανθρώπινης υγείας', 'Other human health activities'),
('Άλλες δραστηριότητες αποκλειστικού(-ης) νοσοκόμου κατ'' οίκον', 'Other home care activities by nurses'),
('Άλλες δραστηριότητες διασκέδασης και ψυχαγωγίας', 'Other amusement and recreation activities'),
('Άλλες δραστηριότητες καθαρισμού', 'Other cleaning activities'),
('Άλλες δραστηριότητες καθαρισμού κτιρίων και βιομηχανικού καθαρισμού', 'Other building and industrial cleaning activities'),
('Άλλες δραστηριότητες κοινωνικής μέριμνας χωρίς παροχή καταλύματος π.δ.κ.α.', 'Other social work activities without accommodation n.e.c.'),
('Άλλες δραστηριότητες παροχής προσωπικών υπηρεσιών π.δ.κ.α.', 'Other personal service activities n.e.c.'),
('Άλλες δραστηριότητες παροχής υπηρεσιών προς τις επιχειρήσεις π.δ.κ.α.', 'Other business support service activities n.e.c.'),
('Άλλες δραστηριότητες συναφείς προς τις ασφαλίσεις και τα συνταξιοδοτικά ταμεία', 'Other activities auxiliary to insurance and pension funding'),
('Άλλες δραστηριότητες συναφείς προς τις χρηματοπιστωτικές υπηρεσίες, με εξαίρεση τις ασφαλιστικές δραστηριότητες και τα συνταξιοδοτικά ταμεία', 'Other activities auxiliary to financial services, except insurance and pension funding'),
('Άλλες δραστηριότητες της τεχνολογίας της πληροφορίας και δραστηριότητες υπηρεσιών ηλεκτρονικών υπολογιστών', 'Other information technology and computer service activities'),
('Άλλες δραστηριότητες υπηρεσιών κρατήσεων και συναφείς δραστηριότητες', 'Other reservation service and related activities'),
('Άλλες δραστηριότητες υπηρεσιών πληροφορίας π.δ.κ.α.', 'Other information service activities n.e.c.'),
('Άλλες δραστηριότητες χρηματοπιστωτικών υπηρεσιών, με εξαίρεση τις ασφάλειες και τα συνταξιοδοτικά ταμεία π.δ.κ.α.', 'Other financial service activities, except insurance and pension funding n.e.c.'),
('Άλλες εκδοτικές δραστηριότητες', 'Other publishing activities'),
('Άλλες εκτυπωτικές δραστηριότητες', 'Other printing activities'),
('Άλλες εξειδικευμένες κατασκευαστικές δραστηριότητες π.δ.κ.α.', 'Other specialized construction activities n.e.c.'),
('Άλλες επαγγελματικές, επιστημονικές και τεχνικές δραστηριότητες π.δ.κ.α.', 'Other professional, scientific and technical activities n.e.c.'),
('Άλλες κατασκευαστικές εγκαταστάσεις', 'Other construction installations'),
('Άλλες κατασκευαστικές εργασίες ολοκλήρωσης και τελειώματος', 'Other completion and finishing works'),
('Άλλες μεταποιητικές δραστηριότητες π.δ.κ.α.', 'Other manufacturing n.e.c.'),
('Άλλες πιστωτικές δραστηριότητες', 'Other credit granting'),
('Άλλες πολυετείς καλλιέργειες', 'Other perennial crops'),
('Άλλες ταχυδρομικές και ταχυμεταφορικές δραστηριότητες', 'Other postal and courier activities'),
('Άλλες τηλεπικοινωνιακές δραστηριότητες', 'Other telecommunications activities'),
('Άλλες υπηρεσίες εστίασης', 'Other food service activities'),
('Άλλες υποστηρικτικές προς τη μεταφορά δραστηριότητες', 'Other transport support activities'),
('Άλλες χερσαίες μεταφορές επιβατών π.δ.κ.α.', 'Other land transport of passengers n.e.c.'),
('Άλλη διάθεση ανθρώπινου δυναμικού', 'Other human resources provision'),
('Άλλη εκπαίδευση π.δ.κ.α.', 'Other education n.e.c.'),
('Άλλη επεξεργασία και συντήρηση φρούτων και λαχανικών', 'Other processing and preserving of fruit and vegetables'),
('Άλλο λιανικό εμπόριο εκτός καταστημάτων, υπαίθριων πάγκων ή αγορών', 'Other retail sale not in stores, stalls or markets'),
('Άλλο λιανικό εμπόριο καινούργιων ειδών σε ειδικευμένα καταστήματα', 'Other retail sale of new goods in specialized stores'),
('Άλλο λιανικό εμπόριο σε μη ειδικευμένα καταστήματα', 'Other retail sale in non-specialized stores'),
('Άλλοι οργανισμοί νομισματικής διαμεσολάβησης', 'Other monetary intermediation'),
('Ανάκτηση διαλεγμένου υλικού', 'Recovery of sorted materials'),
('Αναπαραγωγή προεγγεγραμμένων μέσων', 'Reproduction of recorded media'),
('Ανάπτυξη οικοδομικών σχεδίων', 'Development of building projects'),
('Ανθρακωρυχεία', 'Mining of hard coal'),
('Αποθήκευση', 'Warehousing and storage'),
('Αποκομιδή μη επικίνδυνων αποβλήτων', 'Collection of non-hazardous waste'),
('Αρτοποιία· παραγωγή νωπών ειδών ζαχαροπλαστικής', 'Manufacture of bread; manufacture of fresh pastry goods'),
('Αρχιτεκτονικές δραστηριότητες', 'Architectural activities'),
('Ασφάλειες ζωής', 'Life insurance'),
('Ασφαλίσεις εκτός από ασφάλειες ζωής', 'Non-life insurance'),
('Αστικές και υπεραστικές χερσαίες μεταφορές επιβατών', 'Urban and suburban land transport of passengers'),
('Βιβλιοθήκες και αρχεία', 'Libraries and archives'),
('Δημιουργικές δραστηριότητες, δραστηριότητες στον τομέα της τέχνης και του θεάματος', 'Creative, arts and entertainment activities'),
('Δημοσιογραφικές δραστηριότητες', 'News agency activities'),
('Δευτεροβάθμια γενική εκπαίδευση', 'General secondary education'),
('Δευτεροβάθμια τεχνική και επαγγελματική εκπαίδευση', 'Technical and vocational secondary education'),
('Διαμεσολάβηση σε συναλλαγές επί τίτλων και σε συναλλαγές επί εμπορευμάτων', 'Security and commodity dealing'),
('Διαχείριση αγορών', 'Management of markets'),
('Διαχείριση ακίνητης περιουσίας έναντι αμοιβής ή βάσει σύμβασης', 'Real estate management on a fee or contract basis'),
('Δραστηριότητες ανταλλακτηρίων συναλλάγματος', 'Activities of foreign exchange bureaux'),
('Δραστηριότητες αρχηγείων (κεντρικών γραφείων)', 'Activities of head offices'),
('Δραστηριότητες ασφαλιστικών πρακτόρων και μεσιτών', 'Activities of insurance agents and brokers'),
('Δραστηριότητες βιβλιοθηκών και αρχείων', 'Library and archive activities'),
('Δραστηριότητες γραφείων ταξιδιών και ξεναγών', 'Activities of travel agency and tour operator'),
('Δραστηριότητες εμπορικών εκθέσεων και συνεδρίων', 'Activities of trade fairs and conventions'),
('Δραστηριότητες εξωτερικής αξιολόγησης κινδύνου και ζημιών', 'Risk and damage evaluation activities'),
('Δραστηριότητες εταιρειών χαρτοφυλακίου', 'Activities of holding companies'),
('Δραστηριότητες ζωολογικών και βοτανικών κήπων και φυσικών αποθεμάτων', 'Activities of botanical and zoological gardens and nature reserves'),
('Δραστηριότητες ιδιωτικών νοσοκομείων', 'Activities of private hospitals'),
('Δραστηριότητες καλλιτεχνικής δημιουργίας', 'Artistic creation activities'),
('Δραστηριότητες μουσείων', 'Museum activities'),
('Δραστηριότητες νοικοκυριών ως εργοδοτών οικιακού προσωπικού', 'Activities of households as employers of domestic personnel'),
('Δραστηριότητες οδοντιατρικής πρακτικής', 'Dental practice activities'),
('Δραστηριότητες οργάνωσης συνεδρίων και εμπορικών εκθέσεων', 'Organization of conventions and trade shows'),
('Δραστηριότητες παροχής εξειδικευμένων υπηρεσιών σχεδιασμού', 'Specialized design activities'),
('Δραστηριότητες προσωρινής απασχόλησης', 'Temporary employment agency activities'),
('Δραστηριότητες σχεδιαστών μόδας', 'Fashion design activities'),
('Δραστηριότητες τράπεζας τροφίμων', 'Food bank activities'),
('Δραστηριότητες τυχερών παιχνιδιών και στοιχημάτων', 'Gambling and betting activities'),
('Δραστηριότητες υπηρεσιών συστημάτων προστασίας', 'Security systems service activities'),
('Δραστηριότητες φυτωρίων, εκτός δασικών φυτωρίων', 'Operation of nurseries, except forest nurseries'),
('Δραστηριότητες φωτογραφίας', 'Photographic activities'),
('Εγκατάσταση βιομηχανικών μηχανημάτων και εξοπλισμού', 'Installation of industrial machinery and equipment'),
('Εγκαταστάσεις ύδρευσης, θέρμανσης και κλιματισμού', 'Plumbing, heat and air-conditioning installation'),
('Εκδοτικές δραστηριότητες λοιπού λογισμικού', 'Other software publishing'),
('Εκπαίδευση μέσω αλληλογραφίας ή άλλων μέσων', 'Distance education'),
('Εκπομπή ραδιοφωνικού προγράμματος', 'Radio broadcasting'),
('Εκτύπωση εφημερίδων', 'Printing of newspapers'),
('Εκτύπωση περιοδικών εκδόσεων και λοιπών εκδόσεων', 'Printing of periodicals and other publications'),
('Εμπορικοί αντιπρόσωποι που μεσολαβούν στην πώληση αγαθών γενικού εμπορίου', 'Commercial agents in the sale of a variety of goods'),
('Εμπορικοί αντιπρόσωποι που μεσολαβούν στην πώληση αγροτικών πρώτων υλών, ζώντων ζώων, κλωστοϋφαντουργικών πρώτων υλών και ημικατεργασμένων αγαθών', 'Commercial agents in the sale of agricultural raw materials, live animals, textile raw materials and semi-finished goods'),
('Εμπορικοί αντιπρόσωποι που μεσολαβούν στην πώληση επίπλων, ειδών οικιακής χρήσης και σιδηρικών', 'Commercial agents in the sale of furniture, household goods and hardware'),
('Εμπορικοί αντιπρόσωποι που μεσολαβούν στην πώληση καυσίμων, μεταλλευμάτων, μετάλλων και βιομηχανικών χημικών προϊόντων', 'Commercial agents in the sale of fuels, ores, metals and industrial chemicals'),
('Εμπορικοί αντιπρόσωποι που μεσολαβούν στην πώληση κλωστοϋφαντουργικών προϊόντων, ειδών ένδυσης, γουναρικών, υποδημάτων και δερμάτινων ειδών', 'Commercial agents in the sale of textiles, clothing, fur, footwear and leather goods'),
('Εμπορικοί αντιπρόσωποι που μεσολαβούν στην πώληση μηχανημάτων, βιομηχανικού εξοπλισμού, πλοίων και αεροσκαφών', 'Commercial agents in the sale of machinery, industrial equipment, ships and aircraft'),
('Εμπορικοί αντιπρόσωποι που μεσολαβούν στην πώληση ξυλείας και οικοδομικών υλικών', 'Commercial agents in the sale of timber and building materials'),
('Εμπορικοί αντιπρόσωποι που μεσολαβούν στην πώληση τροφίμων, ποτών και καπνού', 'Commercial agents involved in the sale of food, beverages and tobacco'),
('Εμπόριο ηλεκτρικού ρεύματος', 'Trade of electricity'),
('Ενοικίαση και εκμίσθωση άλλων ειδών προσωπικής ή οικιακής χρήσης', 'Rental and leasing of other personal or household goods'),
('Ενοικίαση και εκμίσθωση άλλων μηχανημάτων, ειδών εξοπλισμού και υλικών αγαθών π.δ.κ.α.', 'Rental and leasing of other machinery, equipment and tangible goods n.e.c.'),
('Ενοικίαση και εκμίσθωση αυτοκινήτων και ελαφρών μηχανοκίνητων οχημάτων', 'Rental and leasing of cars and light motor vehicles'),
('Ενοικίαση και εκμίσθωση ειδών αναψυχής και αθλητικών ειδών', 'Rental and leasing of leisure and sports goods'),
('Ενοικίαση και εκμίσθωση εξοπλισμού αεροπορικών μεταφορών', 'Rental and leasing of air transport equipment'),
('Ενοικίαση και εκμίσθωση μηχανημάτων και εξοπλισμού κατασκευών και έργων πολιτικού μηχανικού', 'Rental and leasing of construction and civil engineering machinery and equipment'),
('Ενοικίαση και εκμίσθωση φορτηγών', 'Rental and leasing of trucks'),
('Εξόρυξη διακοσμητικών και οικοδομικών λίθων, ασβεστόλιθου, γύψου, κιμωλίας και σχιστόλιθου', 'Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate'),
('Εξόρυξη ορυκτών για τη χημική βιομηχανία και τη βιομηχανία λιπασμάτων', 'Mining of chemical and fertilizer minerals'),
('Επενδύσεις δαπέδων και τοίχων', 'Floor and wall covering'),
('Επεξεργασία δεδομένων, καταχώρηση και συναφείς δραστηριότητες', 'Data processing, hosting and related activities'),
('Επεξεργασία και διάθεση επικίνδυνων αποβλήτων', 'Treatment and disposal of hazardous waste'),
('Επεξεργασία και διάθεση μη επικίνδυνων αποβλήτων', 'Treatment and disposal of non-hazardous waste'),
('Επεξεργασία και συντήρηση κρέατος', 'Processing and preserving of meat'),
('Επεξεργασία και συντήρηση κρέατος πουλερικών', 'Processing and preserving of poultry meat'),
('Επεξεργασία και συντήρηση πατατών', 'Processing and preserving of potatoes'),
('Επεξεργασία και συντήρηση ψαριών, καρκινοειδών και μαλακίων', 'Processing and preserving of fish, crustaceans and molluscs'),
('Επεξεργασία λυμάτων', 'Sewerage'),
('Επεξεργασία σπόρων πολλαπλασιασμού', 'Processing of seeds for propagation'),
('Επεξεργασία τσαγιού και καφέ', 'Processing of tea and coffee'),
('Επιδιόρθωση υποδημάτων και δερμάτινων ειδών', 'Repair of footwear and leather goods'),
('Επισκευή άλλου εξοπλισμού', 'Repair of other equipment'),
('Επισκευή άλλων ειδών προσωπικής και οικιακής χρήσης', 'Repair of other personal and household goods'),
('Επισκευή εξοπλισμού επικοινωνίας', 'Repair of communication equipment'),
('Επισκευή επίπλων και ειδών οικιακής επίπλωσης', 'Repair of furniture and home furnishings'),
('Επισκευή ηλεκτρικού εξοπλισμού', 'Repair of electrical equipment'),
('Επισκευή ηλεκτρονικού και οπτικού εξοπλισμού', 'Repair of electronic and optical equipment'),
('Επισκευή ηλεκτρονικών ειδών ευρείας κατανάλωσης', 'Repair of consumer electronics'),
('Επισκευή ηλεκτρονικών υπολογιστών και περιφερειακού εξοπλισμού', 'Repair of computers and peripheral equipment'),
('Επισκευή και συντήρηση αεροσκαφών και διαστημοπλοίων', 'Repair and maintenance of aircraft and spacecraft'),
('Επισκευή και συντήρηση πλοίων και σκαφών', 'Repair and maintenance of ships and boats'),
('Επισκευή μεταλλικών προϊόντων', 'Repair of fabricated metal products'),
('Επισκευή μηχανημάτων', 'Repair of machinery'),
('Επισκευή ρολογιών και κοσμημάτων', 'Repair of watches and jewellery'),
('Επισκευή συσκευών οικιακής χρήσης και εξοπλισμού σπιτιού και κήπου', 'Repair of household appliances and home and garden equipment'),
('Επιχρίσεις κονιαμάτων', 'Plastering'),
('Έρευνα αγοράς και δημοσκοπήσεις', 'Market research and public opinion polling'),
('Έρευνα και πειραματική ανάπτυξη σε άλλες φυσικές επιστήμες και τη μηχανική', 'Research and experimental development on other natural sciences and engineering'),
('Έρευνα και πειραματική ανάπτυξη στη βιοτεχνολογία', 'Research and experimental development in biotechnology'),
('Έρευνα και πειραματική ανάπτυξη στις κοινωνικές και ανθρωπιστικές επιστήμες', 'Research and experimental development on social sciences and humanities'),
('Ζυθοποιία', 'Manufacture of beer'),
('Ηλεκτρικές εγκαταστάσεις', 'Electrical installation'),
('Θαλάσσιες και ακτοπλοϊκές μεταφορές εμπορευμάτων', 'Sea and coastal freight water transport'),
('Θαλάσσιες και ακτοπλοϊκές μεταφορές επιβατών', 'Sea and coastal passenger water transport'),
('Ιατρική πρακτική', 'Medical practice'),
('Καθαρισμός και στίλβωση', 'Cleaning and polishing'),
('Καλλιέργεια αμπελιών', 'Growing of grapes'),
('Καλλιέργεια δημητριακών (εκτός ρυζιού), οσπρίων και ελαιούχων σπόρων', 'Growing of cereals (except rice), leguminous crops and oil seeds'),
('Καλλιέργεια εσπεριδοειδών', 'Growing of citrus fruits'),
('Καλλιέργεια ζαχαροτεύτλων', 'Growing of sugar beet'),
('Καλλιέργεια καπνού', 'Growing of tobacco'),
('Καλλιέργεια κηπευτικών, πεπονοειδών, ριζωδών φυτών και βολβών', 'Growing of vegetables, melons, roots and tubers'),
('Καλλιέργεια λαχανικών και πεπονοειδών, ριζών και κονδύλων', 'Growing of vegetables and melons, roots and tubers'),
('Καλλιέργεια μπαχαρικών, αρωματικών φυτών', 'Growing of spices and aromatic plants'),
('Καλλιέργεια πυρηνόκαρπων και μηλοειδών', 'Growing of pome fruits and stone fruits'),
('Καλλιέργεια ρυζιού', 'Growing of rice'),
('Καλλιέργεια τροπικών και υποτροπικών φρούτων', 'Growing of tropical and subtropical fruits'),
('Καλλιέργεια φυτών για την παρασκευή ροφημάτων', 'Growing of beverage crops'),
('Κατασκευαστικές δραστηριότητες', 'Construction activities'),
('Κατασκευαστικές εργασίες που αφορούν πετρελαιαγωγούς, αγωγούς επικοινωνίας και ηλεκτρικής ενέργειας, αγωγούς αστικών δικτύων', 'Construction of utility projects for fluids, electricity and telecommunications'),
('Κατασκευή αθλητικών ειδών', 'Manufacture of sports goods'),
('Κατασκευή αλλαντικών', 'Manufacture of sausages'),
('Κατασκευή άλλων ειδών ένδυσης και εξαρτημάτων ένδυσης', 'Manufacture of other wearing apparel and accessories'),
('Κατασκευή άλλων ειδών μεταφοράς π.δ.κ.α.', 'Manufacture of other transport equipment n.e.c.'),
('Κατασκευή άλλων ειδών σκυροδέματος, γύψου και τσιμέντου', 'Manufacture of other articles of concrete, plaster and cement'),
('Κατασκευή άλλων ηλεκτρικών ειδών', 'Manufacture of other electrical equipment'),
('Κατασκευή άλλων μη μεταλλικών ορυκτών προϊόντων π.δ.κ.α.', 'Manufacture of other non-metallic mineral products n.e.c.'),
('Κατασκευή άλλων μηχανημάτων γενικής χρήσης', 'Manufacture of other general-purpose machinery'),
('Κατασκευή άλλων μηχανημάτων ειδικής χρήσης', 'Manufacture of other special-purpose machinery'),
('Κατασκευή άλλων πλαστικών προϊόντων', 'Manufacture of other plastic products'),
('Κατασκευή άλλων προϊόντων από μη μεταλλικά ορυκτά π.δ.κ.α.', 'Manufacture of other non-metallic mineral products n.e.c.'),
('Κατασκευή άλλων προϊόντων από ξύλο· κατασκευή ειδών από φελλό και ειδών καλαθοποιίας και σπαρτοπλεκτικής', 'Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials'),
('Κατασκευή άλλων προϊόντων από χαρτί και χαρτόνι', 'Manufacture of other articles of paper and paperboard'),
('Κατασκευή άλλων τροφίμων π.δ.κ.α.', 'Manufacture of other food products n.e.c.'),
('Κατασκευή άλλων χημικών προϊόντων π.δ.κ.α.', 'Manufacture of other chemical products n.e.c.'),
('Κατασκευή αμαξωμάτων οχημάτων με κινητήρα, κατασκευή ρυμουλκούμενων και ημιρυμουλκούμενων οχημάτων', 'Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers'),
('Κατασκευή ανελκυστήρων και κυλιόμενων κλιμάκων', 'Manufacture of lifting and handling equipment'),
('Κατασκευή αποσκευών, τσαντών και παρόμοιων ειδών, ειδών σελοποιίας και σαγματοποιίας', 'Manufacture of luggage, handbags and the like, saddlery and harness'),
('Κατασκευή γεωργικών και δασοκομικών μηχανημάτων', 'Manufacture of agricultural and forestry machinery'),
('Κατασκευή γυαλιού και προϊόντων υαλουργίας', 'Manufacture of glass and glass products'),
('Κατασκευή γυαλιού και προϊόντων υαλουργίας (εκτός από κούφια ή εξαρτήματα)', 'Manufacture of glass and glass products (other than hollow or parts)'),
('Κατασκευή δοχείων από μέταλλο', 'Manufacture of metal containers'),
('Κατασκευή δομικών μεταλλικών προϊόντων', 'Manufacture of structural metal products'),
('Κατασκευή ειδών ατομικής χρήσης και οικιακής χρήσης από πλαστικές ύλες', 'Manufacture of plastic household and personal goods'),
('Κατασκευή ειδών κοσμηματοποιίας και συναφών ειδών', 'Manufacture of jewellery and related articles'),
('Κατασκευή ειδών υπόδησης', 'Manufacture of footwear'),
('Κατασκευή εξαρτημάτων και ανταλλακτικών μηχανοκίνητων οχημάτων', 'Manufacture of parts and accessories for motor vehicles'),
('Κατασκευή επίπλων', 'Manufacture of furniture'),
('Κατασκευή επίπλων για γραφεία και καταστήματα', 'Manufacture of office and shop furniture'),
('Κατασκευή ετοίμου σκυροδέματος (μπετόν)', 'Manufacture of ready-mixed concrete'),
('Κατασκευή ηλεκτρικών φωτιστικών ειδών', 'Manufacture of electric lighting equipment'),
('Κατασκευή ηλεκτρικού εξοπλισμού για κινητήρες, ηλεκτρογεννήτριες και μετασχηματιστές ρεύματος', 'Manufacture of electric motors, generators and transformers'),
('Κατασκευή ηλεκτρονικών ειδών ευρείας κατανάλωσης', 'Manufacture of consumer electronics'),
('Κατασκευή ηλεκτρονικών στοιχείων', 'Manufacture of electronic components'),
('Κατασκευή ηλεκτρονικών υπολογιστών και περιφερειακού εξοπλισμού', 'Manufacture of computers and peripheral equipment'),
('Κατασκευή θυρών και παραθύρων από μέταλλο', 'Manufacture of metal doors and windows'),
('Κατασκευή ιατρικών εργαλείων, συσκευών και προμηθειών', 'Manufacture of medical instruments, appliances and supplies'),
('Κατασκευή κεραμικών πλακιδίων και πλακών', 'Manufacture of ceramic tiles and flags'),
('Κατασκευή κλιματιστικών μηχανημάτων', 'Manufacture of air conditioning equipment'),
('Κατασκευή κοσμημάτων από πολύτιμα μέταλλα ή επενδεδυμένα με πολύτιμα μέταλλα', 'Manufacture of jewellery from precious metals or clad with precious metals'),
('Κατασκευή κουζινών', 'Manufacture of kitchen furniture'),
('Κατασκευή κυματοειδούς χαρτιού και χαρτονιού και δοχείων από χαρτί και χαρτόνι', 'Manufacture of corrugated paper and paperboard and of containers of paper and paperboard'),
('Κατασκευή μεταλλικών δεξαμενών, δοχείων και δοχείων ατμού', 'Manufacture of tanks, reservoirs and containers of metal'),
('Κατασκευή μεταλλικών σκελετών και μερών μεταλλικών σκελετών', 'Manufacture of metal frameworks and parts of metal frameworks'),
('Κατασκευή μηχανημάτων για τη βιομηχανία τροφίμων, ποτών και καπνού', 'Manufacture of machinery for food, beverage and tobacco processing'),
('Κατασκευή μηχανημάτων μορφοποίησης μετάλλων και εργαλειομηχανών', 'Manufacture of metal forming machinery and machine tools'),
('Κατασκευή μπαταριών και συσσωρευτών', 'Manufacture of batteries and accumulators'),
('Κατασκευή ξύλινων δοχείων', 'Manufacture of wooden containers'),
('Κατασκευή οπτικών οργάνων και φωτογραφικού εξοπλισμού', 'Manufacture of optical instruments and photographic equipment'),
('Κατασκευή παιχνιδιών κάθε είδους', 'Manufacture of games and toys'),
('Κατασκευή πλαστικών πλακών, φύλλων, σωλήνων και μορφοσωλήνων', 'Manufacture of plastic plates, sheets, tubes and profiles'),
('Κατασκευή πλαστικών υλικών συσκευασίας', 'Manufacture of plastic packing goods'),
('Κατασκευή προϊόντων από σκυρόδεμα για δομικές κατασκευές', 'Manufacture of concrete products for construction purposes'),
('Κατασκευή σαπουνιών και απορρυπαντικών, προϊόντων καθαρισμού και στίλβωσης, αρωμάτων και παρασκευασμάτων καλλωπισμού', 'Manufacture of soap and detergents, cleaning and polishing preparations, perfumes and toilet preparations'),
('Κατασκευή στρωμάτων', 'Manufacture of mattresses'),
('Κατασκευή συνθετικών ινών', 'Manufacture of man-made fibres'),
('Κατασκευή σχοινιών, σπάγκων, κλωστών και διχτιών', 'Manufacture of cordage, rope, twine and netting'),
('Κατασκευή υδραυλικού και πνευματικού εξοπλισμού', 'Manufacture of hydraulic and pneumatic equipment'),
('Κατασκευή χαρτοπολτού, χαρτιού και χαρτονιού', 'Manufacture of pulp, paper and paperboard'),
('Κατασκευή χρωμάτων, βερνικιών και παρόμοιων επιχρισμάτων, μελανιών τυπογραφίας και μαστιχών', 'Manufacture of paints, varnishes and similar coatings, printing ink and mastics'),
('Κατεδαφίσεις', 'Demolition'),
('Κατεργασία και βαφή γουναρικών', 'Processing and dyeing of fur'),
('Κατεργασία και δέψη δερμάτων· κατεργασία και βαφή γουναρικών', 'Tanning and dressing of leather; dressing and dyeing of fur'),
('Κατεργασία νημάτων κλωστοϋφαντουργικών υλών', 'Preparation and spinning of textile fibres'),
('Κοπτική και ραπτική', 'Cutting and sewing'),
('Λειτουργία αθλητικών εγκαταστάσεων', 'Operation of sports facilities'),
('Λιανικό εμπόριο ανταλλακτικών αυτοκινήτων', 'Retail sale of automotive parts and accessories'),
('Λιανικό εμπόριο ενδυμάτων σε ειδικευμένα καταστήματα', 'Retail sale of clothing in specialised stores'),
('Λιανικό εμπόριο εξοπλισμού ήχου και εικόνας σε ειδικευμένα καταστήματα', 'Retail sale of audio and video equipment in specialised stores'),
('Λιανικό εμπόριο επίπλων, φωτιστικών και άλλων ειδών οικιακής χρήσης σε ειδικευμένα καταστήματα', 'Retail sale of furniture, lighting equipment and other household articles in specialised stores'),
('Λιανικό εμπόριο εφημερίδων και γραφικής ύλης σε ειδικευμένα καταστήματα', 'Retail sale of newspapers and stationery in specialised stores'),
('Λιανικό εμπόριο ηλεκτρικών οικιακών συσκευών σε ειδικευμένα καταστήματα', 'Retail sale of electrical household appliances in specialised stores'),
('Λιανικό εμπόριο ηλεκτρονικών υπολογιστών, περιφερειακών μονάδων υπολογιστών και λογισμικού σε ειδικευμένα καταστήματα', 'Retail sale of computers, peripheral units and software in specialised stores'),
('Λιανικό εμπόριο ιατρικών και ορθοπεδικών ειδών σε ειδικευμένα καταστήματα', 'Retail sale of medical and orthopaedic goods in specialised stores'),
('Λιανικό εμπόριο καλλυντικών και ειδών καλλωπισμού σε ειδικευμένα καταστήματα', 'Retail sale of cosmetic and toilet articles in specialised stores'),
('Λιανικό εμπόριο καυσίμων κίνησης σε ειδικευμένα καταστήματα', 'Retail sale of automotive fuel in specialised stores'),
('Λιανικό εμπόριο κλωστοϋφαντουργικών προϊόντων σε ειδικευμένα καταστήματα', 'Retail sale of textiles in specialised stores'),
('Λιανικό εμπόριο κρέατος και προϊόντων κρέατος σε ειδικευμένα καταστήματα', 'Retail sale of meat and meat products in specialised stores'),
('Λιανικό εμπόριο λουλουδιών, φυτών, σπόρων, λιπασμάτων, ζώων συντροφιάς και σχετικών ζωοτροφών σε ειδικευμένα καταστήματα', 'Retail sale of flowers, plants, seeds, fertilizers, pet animals and related food in specialised stores'),
('Λιανικό εμπόριο μερών, εξαρτημάτων και αξεσουάρ αυτοκινήτων και άλλων μηχανοκίνητων οχημάτων', 'Retail sale of motor vehicle parts, components and accessories'),
('Λιανικό εμπόριο μεταχειρισμένων ειδών σε καταστήματα', 'Retail sale of second-hand goods in stores'),
('Λιανικό εμπόριο παιχνιδιών κάθε είδους σε ειδικευμένα καταστήματα', 'Retail sale of games and toys in specialised stores'),
('Λιανικό εμπόριο ποτών σε ειδικευμένα καταστήματα', 'Retail sale of beverages in specialised stores'),
('Λιανικό εμπόριο προϊόντων καπνού σε ειδικευμένα καταστήματα', 'Retail sale of tobacco products in specialised stores'),
('Λιανικό εμπόριο ρολογιών και κοσμημάτων σε ειδικευμένα καταστήματα', 'Retail sale of watches and jewellery in specialised stores'),
('Λιανικό εμπόριο σε μη ειδικευμένα καταστήματα που πωλούν κυρίως τρόφιμα, ποτά ή καπνό', 'Retail sale in non-specialised stores with food, beverages or tobacco predominating'),
('Λιανικό εμπόριο σιδηρικών, χρωμάτων και τζαμιών σε ειδικευμένα καταστήματα', 'Retail sale of hardware, paints and glass in specialised stores'),
('Λιανικό εμπόριο τηλεπικοινωνιακού εξοπλισμού σε ειδικευμένα καταστήματα', 'Retail sale of telecommunications equipment in specialised stores'),
('Λιανικό εμπόριο τροφίμων, ποτών και καπνού σε υπαίθριους πάγκους και αγορές', 'Retail sale of food, beverages and tobacco via stalls and markets'),
('Λιανικό εμπόριο υποδημάτων και δερμάτινων ειδών σε ειδικευμένα καταστήματα', 'Retail sale of footwear and leather goods in specialised stores'),
('Λιανικό εμπόριο φρούτων και λαχανικών σε ειδικευμένα καταστήματα', 'Retail sale of fruit and vegetables in specialised stores'),
('Λιανικό εμπόριο χαλιών, κιλιμιών και επενδύσεων δαπέδου και τοίχου σε ειδικευμένα καταστήματα', 'Retail sale of carpets, rugs, wall and floor coverings in specialised stores'),
('Λιανικό εμπόριο ψαριών, καρκινοειδών και μαλακίων σε ειδικευμένα καταστήματα', 'Retail sale of fish, crustaceans and molluscs in specialised stores'),
('Λιανικό εμπόριο ψωμιού, αρτοσκευασμάτων και λοιπών ειδών αρτοποιίας και ζαχαροπλαστικής σε ειδικευμένα καταστήματα', 'Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores'),
('Μεσιτικά γραφεία ακινήτων', 'Real estate agencies'),
('Μεταδευτεροβάθμια μη τριτοβάθμια εκπαίδευση', 'Post-secondary non-tertiary education'),
('Μεταλλοτεχνία', 'Forging, pressing, stamping and roll-forming of metal; powder metallurgy'),
('Μη ειδικευμένο χονδρικό εμπόριο', 'Non-specialised wholesale trade'),
('Μη ειδικευμένο χονδρικό εμπόριο τροφίμων, ποτών και καπνού', 'Non-specialised wholesale of food, beverages and tobacco'),
('Μικτές γεωργοκτηνοτροφικές δραστηριότητες', 'Mixed farming'),
('Μορφοποίηση και κατεργασία επίπεδου γυαλιού', 'Shaping and processing of flat glass'),
('Ναυπήγηση πλοίων και πλωτών κατασκευών', 'Building of ships and floating structures'),
('Ναυπήγηση σκαφών αναψυχής και αθλητισμού', 'Building of pleasure and sporting boats'),
('Νοσοκομειακές δραστηριότητες', 'Hospital activities'),
('Ξενοδοχεία και παρόμοια καταλύματα', 'Hotels and similar accommodation'),
('Οδικές μεταφορές εμπορευμάτων', 'Freight transport by road'),
('Οινοποιία', 'Manufacture of wine'),
('Ορθοπεδικές δραστηριότητες', 'Orthopaedic activities'),
('Παραγωγή αιθέριων ελαίων', 'Manufacture of essential oils'),
('Παραγωγή άλεσης δημητριακών', 'Milling of cereals'),
('Παραγωγή άλλων χημικών προϊόντων π.δ.κ.α.', 'Manufacture of other chemical products n.e.c.'),
('Παραγωγή αλμύρων και αλατιών', 'Manufacture of condiments and seasonings'),
('Παραγωγή αλουμινίου', 'Aluminium production'),
('Παραγωγή αναψυκτικών· παραγωγή μεταλλικού νερού και άλλων εμφιαλωμένων νερών', 'Manufacture of soft drinks; production of mineral waters and other bottled waters'),
('Παραγωγή αποσταγμάτων, ποτών και μπύρας', 'Manufacture of distilled alcoholic beverages'),
('Παραγωγή γαλακτοκομικών προϊόντων', 'Manufacture of dairy products'),
('Παραγωγή γλυκισμάτων', 'Manufacture of confectionery'),
('Παραγωγή δομικών υλικών από άργιλο', 'Manufacture of clay building materials'),
('Παραγωγή ειδών σιδηρουργίας', 'Manufacture of cutlery, tools and general hardware'),
('Παραγωγή ελαίων και λιπών', 'Manufacture of oils and fats'),
('Παραγωγή εξοπλισμού ακτινοβολίας, ηλεκτροϊατρικού και ηλεκτροθεραπευτικού εξοπλισμού', 'Manufacture of irradiation, electromedical and electrotherapeutic equipment'),
('Παραγωγή ηλεκτρικού ρεύματος', 'Electricity generation'),
('Παραγωγή ζαχαρωδών προϊόντων', 'Manufacture of sugar confectionery'),
('Παραγωγή ζύμης', 'Manufacture of yeast'),
('Παραγωγή ζωοτροφών', 'Manufacture of prepared animal feeds'),
('Παραγωγή κακάο, σοκολάτας και ζαχαρωτών', 'Manufacture of cocoa, chocolate and sugar confectionery'),
('Παραγωγή κεραμικών ειδών οικιακής χρήσης και διακόσμησης', 'Manufacture of ceramic household and ornamental articles'),
('Παραγωγή κοπτικών εργαλείων', 'Manufacture of cutlery'),
('Παραγωγή μακαρονιών, λαζανιών, κουσκούς και παρόμοιων αλευρωδών προϊόντων', 'Manufacture of macaroni, noodles, couscous and similar farinaceous products'),
('Παραγωγή μελιού και κεριού μελισσών', 'Production of honey and beeswax'),
('Παραγωγή μονωτικών υλικών', 'Manufacture of insulating materials'),
('Παραγωγή ξυλείας', 'Sawmilling and planing of wood'),
('Παραγωγή οπτόπλινθων (τούβλων) και κεραμιδιών', 'Manufacture of bricks, tiles and construction products'),
('Παραγωγή παγωτών', 'Manufacture of ice cream'),
('Παραγωγή πάγου', 'Manufacture of ice'),
('Παραγωγή πληροφοριακών και πολιτιστικών προϊόντων', 'Production of information and cultural goods'),
('Παραγωγή πλυντηρίων', 'Manufacture of domestic appliances'),
('Παραγωγή πολτού χαρτιού', 'Manufacture of pulp'),
('Παραγωγή πυρίμαχων προϊόντων', 'Manufacture of refractory products'),
('Παραγωγή σιδήρου και χάλυβα', 'Manufacture of iron and steel'),
('Παραγωγή τσιμέντου', 'Manufacture of cement'),
('Παραγωγή υποδημάτων', 'Manufacture of footwear'),
('Παραγωγή φαρμακευτικών σκευασμάτων', 'Manufacture of pharmaceutical preparations'),
('Παραγωγή χαρτονιού', 'Manufacture of paperboard'),
('Παραγωγή, μετάδοση και διανομή ηλεκτρικής ενέργειας', 'Generation, transmission and distribution of electric power'),
('Παροχή αερίου μέσω αγωγών', 'Distribution of gaseous fuels through mains'),
('Παροχή ιατρικών υπηρεσιών κατ'' οίκον', 'Home health care services'),
('Παροχή καταλύματος για ηλικιωμένους και άτομα με αναπηρίες', 'Residential care for the elderly and disabled'),
('Παροχή υπηρεσιών εστίασης με πλήρη εξυπηρέτηση εστιατορίου', 'Full-service restaurant activities'),
('Πλύση και (στεγνό) καθάρισμα κλωστοϋφαντουργικών και γούνινων προϊόντων', 'Washing and (dry-)cleaning of textile and fur products'),
('Ποδηλάτες, μοτοποδηλάτες, κ.λ.π. - πώληση, συντήρηση, επισκευή', 'Sale, maintenance and repair of motorcycles and related parts'),
('Πριόνισμα, πλάνισμα και εμποτισμός ξύλου', 'Sawmilling and planing of wood'),
('Προβολή κινηματογραφικών ταινιών', 'Motion picture projection activities'),
('Προεπαγγελματική εκπαίδευση', 'Pre-vocational education'),
('Προπαρασκευαστικές εργασίες εργοταξίου', 'Site preparation'),
('Προσχολική εκπαίδευση', 'Pre-primary education'),
('Προσωπική φροντίδα ηλικιωμένων', 'Personal care of the elderly'),
('Πρωτοβάθμια εκπαίδευση', 'Primary education'),
('Πώληση αυτοκινήτων και ελαφρών μηχανοκίνητων οχημάτων', 'Sale of cars and light motor vehicles'),
('Ραδιοφωνικές και τηλεοπτικές εκπομπές', 'Radio and television broadcasting'),
('Ρυμουλκήσεις και ωθήσεις', 'Towing and pushing services'),
('Συλλογή αποβλήτων', 'Waste collection'),
('Συλλογή επικίνδυνων αποβλήτων', 'Collection of hazardous waste'),
('Συμβουλευτικές δραστηριότητες σχετικά με τη διαχείριση', 'Management consultancy activities'),
('Συμβουλευτικές υπηρεσίες στον τομέα της τεχνολογίας πληροφοριών', 'Information technology consultancy'),
('Συντήρηση και επισκευή αυτοκινήτων', 'Maintenance and repair of motor vehicles'),
('Τηλεπικοινωνίες μέσω δικτύων ασύρματης τηλεπικοινωνίας', 'Wireless telecommunications activities'),
('Τηλεπικοινωνίες μέσω δικτύων ενσύρματης τηλεπικοινωνίας', 'Wired telecommunications activities'),
('Τηλεπικοινωνίες μέσω δορυφόρου', 'Satellite telecommunications activities'),
('Τριτοβάθμια εκπαίδευση', 'Tertiary education'),
('Τυποποιημένες δοκιμές και αναλύσεις', 'Technical testing and analysis'),
('Υδρορροές', 'Plumbing'),
('Υπηρεσίες βελτιστοποίησης κτηρίων', 'Building optimization services'),
('Υπηρεσίες διαφήμισης', 'Advertising services'),
('Υπηρεσίες εστίασης βάσει σύμβασης', 'Event catering activities'),
('Υπηρεσίες εστίασης για εκδηλώσεις', 'Event catering'),
('Υπηρεσίες μετάφρασης και διερμηνείας', 'Translation and interpretation activities'),
('Υπηρεσίες παροχής ποτών', 'Beverage serving activities'),
('Υπηρεσίες σχεδιαστών εσωτερικών χώρων', 'Interior design activities'),
('Υπηρεσίες τροφοδοσίας', 'Catering services'),
('Υπηρεσίες φύλαξης και ασφαλείας', 'Security and investigation activities'),
('Φαρμακεία', 'Retail sale in specialised stores (pharmacies)'),
('Φροντίδα παιδιών', 'Child day-care activities'),
('Φωτογραφία', 'Photographic activities'),
('Χαρτογραφικές και χωρικές δραστηριότητες', 'Cartographic and spatial activities'),
('Χερσαίες μεταφορές εμπορευμάτων', 'Freight transport by road'),
('Χονδρικό εμπόριο αγροτικών πρώτων υλών και ζώντων ζώων', 'Wholesale of agricultural raw materials and live animals'),
('Χονδρικό εμπόριο αλκοολούχων ποτών', 'Wholesale of alcoholic beverages'),
('Χονδρικό εμπόριο άλλων ειδών οικιακής χρήσης', 'Wholesale of other household goods'),
('Χονδρικό εμπόριο άλλων ενδιάμεσων προϊόντων', 'Wholesale of other intermediate products'),
('Χονδρικό εμπόριο άλλων μηχανημάτων και εξοπλισμού', 'Wholesale of other machinery and equipment'),
('Χονδρικό εμπόριο άλλων τροφίμων, συμπεριλαμβανομένων ψαριών, καρκινοειδών και μαλακίων', 'Wholesale of other food, including fish, crustaceans and molluscs'),
('Χονδρικό εμπόριο αποβλήτων και υπολειμμάτων', 'Wholesale of waste and scrap'),
('Χονδρικό εμπόριο γαλακτοκομικών προϊόντων, αυγών, βρώσιμων λιπών και ελαίων', 'Wholesale of dairy products, eggs and edible oils and fats'),
('Χονδρικό εμπόριο γεωργικών μηχανημάτων, εξοπλισμού και προμηθειών', 'Wholesale of agricultural machinery, equipment and supplies'),
('Χονδρικό εμπόριο δερμάτων', 'Wholesale of hides, skins and leather'),
('Χονδρικό εμπόριο ειδών ένδυσης και υπόδησης', 'Wholesale of clothing and footwear'),
('Χονδρικό εμπόριο εξορυκτικών μηχανημάτων, καθώς και μηχανημάτων για κατασκευαστικά έργα και έργα πολιτικού μηχανικού', 'Wholesale of mining, construction and civil engineering machinery'),
('Χονδρικό εμπόριο εργαλειομηχανών', 'Wholesale of machine tools'),
('Χονδρικό εμπόριο ζάχαρης, σοκολάτας και ζαχαρωδών προϊόντων', 'Wholesale of sugar, chocolate and sugar confectionery'),
('Χονδρικό εμπόριο ηλεκτρονικών εξαρτημάτων και τηλεπικοινωνιακού εξοπλισμού', 'Wholesale of electronic and telecommunications parts and equipment'),
('Χονδρικό εμπόριο ηλεκτρονικών υπολογιστών, περιφερειακού εξοπλισμού υπολογιστών και λογισμικού', 'Wholesale of computers, computer peripheral equipment and software'),
('Χονδρικό εμπόριο καυσίμων και συναφών προϊόντων', 'Wholesale of solid, liquid and gaseous fuels and related products'),
('Χονδρικό εμπόριο κρέατος και προϊόντων κρέατος', 'Wholesale of meat and meat products'),
('Χονδρικό εμπόριο μεταλλευμάτων και μετάλλων', 'Wholesale of metals and metal ores'),
('Χονδρικό εμπόριο μη αλκοολούχων ποτών', 'Wholesale of non-alcoholic beverages'),
('Χονδρικό εμπόριο μηχανημάτων για τη βιομηχανία κλωστοϋφαντουργικών προϊόντων και ραπτομηχανών', 'Wholesale of textile industry machinery and sewing machines'),
('Χονδρικό εμπόριο μηχανημάτων γραφείου και εξοπλισμού γραφείου', 'Wholesale of office machinery and equipment'),
('Χονδρικό εμπόριο ξυλείας, οικοδομικών υλικών και ειδών υγιεινής', 'Wholesale of wood, construction materials and sanitary equipment'),
('Χονδρικό εμπόριο οικιακών ηλεκτρικών συσκευών', 'Wholesale of electrical household appliances'),
('Χονδρικό εμπόριο πρώτων υλών γεωργίας και ζωικού κεφαλαίου', 'Wholesale of agricultural raw materials and livestock'),
('Χονδρικό εμπόριο σιδηρικών, υδραυλικών ειδών και ειδών θέρμανσης και προμηθειών', 'Wholesale of hardware, plumbing and heating equipment and supplies'),
('Χονδρικό εμπόριο τσιγάρων και καπνού', 'Wholesale of tobacco products'),
('Χονδρικό εμπόριο υφασμάτων', 'Wholesale of textiles'),
('Χονδρικό εμπόριο φαρμακευτικών προϊόντων', 'Wholesale of pharmaceutical goods'),
('Χονδρικό εμπόριο φρούτων και λαχανικών', 'Wholesale of fruit and vegetables'),
('Χονδρικό εμπόριο χημικών προϊόντων', 'Wholesale of chemical products'),
('Χρηματοδοτική μίσθωση (leasing)', 'Financial leasing'),
('Χρηματοπιστωτικές υπηρεσίες', 'Financial service activities'),
('Ψυχαγωγία και αναψυχή', 'Amusement and recreation')
) AS t(gr, en)
WHERE dc.activity_description = t.gr;