-- Use LIKE patterns for entries with special middle dot characters
UPDATE directory_companies SET activity_description = 'Manufacture of bread; manufacture of fresh pastry goods and cakes' WHERE activity_description LIKE 'Αρτοποιία%παραγωγή νωπών ειδών ζαχαροπλαστικής';
UPDATE directory_companies SET activity_description = 'Accounting, bookkeeping and auditing activities; tax consultancy' WHERE activity_description LIKE 'Δραστηριότητες λογιστικής%παροχή φορολογικών συμβουλών';
UPDATE directory_companies SET activity_description = 'Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials' WHERE activity_description LIKE 'Κατασκευή άλλων προϊόντων από ξύλο%κατασκευή ειδών από φελλό%';
UPDATE directory_companies SET activity_description = 'Manufacture of bodies for motor vehicles; manufacture of trailers and semi-trailers' WHERE activity_description LIKE 'Κατασκευή αμαξωμάτων για μηχανοκίνητα οχήματα%κατασκευή ρυμουλκούμενων%';
UPDATE directory_companies SET activity_description = 'Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres' WHERE activity_description LIKE 'Κατασκευή επισώτρων%καουτσούκ%αναγόμωση%';
UPDATE directory_companies SET activity_description = 'Tanning and dressing of leather; dressing and dyeing of fur' WHERE activity_description LIKE 'Κατεργασία και δέψη δέρματος%γουναρικών';
UPDATE directory_companies SET activity_description = 'Operation of gravel and sand pits; mining of clays and kaolin' WHERE activity_description LIKE 'Λειτουργία φρεάτων παραγωγής αμμοχάλικου%';
UPDATE directory_companies SET activity_description = 'Manufacture of soft drinks; production of mineral waters and other bottled waters' WHERE activity_description LIKE 'Παραγωγή αναψυκτικών%μεταλλικού νερού%';
UPDATE directory_companies SET activity_description = 'Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes' WHERE activity_description LIKE 'Παραγωγή παξιμαδιών και μπισκότων%';
UPDATE directory_companies SET activity_description = 'Sale of other motor vehicles' WHERE activity_description = 'Πώληση άλλων μηχανοκίνητων οχημάτων';
UPDATE directory_companies SET activity_description = 'Sale, maintenance and repair of motorcycles and related parts and accessories' WHERE activity_description LIKE 'Πώληση, συντήρηση και επισκευή μοτοσικλετών%';
UPDATE directory_companies SET activity_description = 'Regulation of and contribution to more efficient operation of businesses' WHERE activity_description LIKE 'Ρύθμιση των επιχειρηματικών δραστηριοτήτων%';
UPDATE directory_companies SET activity_description = 'Collection of non-hazardous waste' WHERE activity_description LIKE 'Συλλογή μη επικίνδυνων αποβλήτων';
UPDATE directory_companies SET activity_description = 'Water collection, treatment and supply' WHERE activity_description LIKE 'Συλλογή, επεξεργασία και παροχή νερού';
UPDATE directory_companies SET activity_description = 'Combined office administrative service activities' WHERE activity_description LIKE 'Συνδυασμένες διοικητικές δραστηριότητες γραφείου';
UPDATE directory_companies SET activity_description = 'Pension funding' WHERE activity_description = 'Συνταξιοδοτικά ταμεία';
UPDATE directory_companies SET activity_description = 'Finishing of textiles' WHERE activity_description LIKE 'Τελειοποίηση%υφαντουργικών προϊόντων';
UPDATE directory_companies SET activity_description = 'Performing arts' WHERE activity_description = 'Τέχνες του θεάματος';
UPDATE directory_companies SET activity_description = 'Technical and vocational secondary education' WHERE activity_description LIKE 'Τεχνική και επαγγελματική δευτεροβάθμια%';
UPDATE directory_companies SET activity_description = 'Gambling and betting activities' WHERE activity_description LIKE 'Τυχερά παιχνίδια και στοιχήματα';
UPDATE directory_companies SET activity_description = 'Freshwater aquaculture' WHERE activity_description LIKE 'Υδατοκαλλιέργεια γλυκών υδάτων';
UPDATE directory_companies SET activity_description = 'Plumbing, heat and air-conditioning installation' WHERE activity_description LIKE 'Υδραυλικές και κλιματιστικές εγκαταστάσεις%';
UPDATE directory_companies SET activity_description = 'Logging' WHERE activity_description = 'Υλοτομία';
UPDATE directory_companies SET activity_description = 'Computer facilities management activities' WHERE activity_description LIKE 'Υπηρεσίες διαχείρισης ηλεκτρονικών συστημάτων';
UPDATE directory_companies SET activity_description = 'Removal services' WHERE activity_description LIKE 'Υπηρεσίες μετακόμισης';
UPDATE directory_companies SET activity_description = 'Support activities for animal production' WHERE activity_description LIKE 'Υποστηρικτικές δραστηριότητες για τη ζωική παραγωγή';
UPDATE directory_companies SET activity_description = 'Support activities for crop production' WHERE activity_description LIKE 'Υποστηρικτικές δραστηριότητες για τη φυτική παραγωγή';
UPDATE directory_companies SET activity_description = 'Support activities for petroleum and natural gas extraction' WHERE activity_description LIKE 'Υποστηρικτικές δραστηριότητες για την άντληση πετρελαίου%';
UPDATE directory_companies SET activity_description = 'Support activities to performing arts' WHERE activity_description LIKE 'Υποστηρικτικές δραστηριότητες για τις τέχνες%';
UPDATE directory_companies SET activity_description = 'Support services to forestry' WHERE activity_description LIKE 'Υποστηρικτικές προς τη δασοκομία%';
UPDATE directory_companies SET activity_description = 'Weaving of textiles' WHERE activity_description LIKE 'Ύφανση κλωστοϋφαντουργικών%';
UPDATE directory_companies SET activity_description = 'Dispensing chemist in specialised stores' WHERE activity_description LIKE 'Φαρμακευτικά είδη σε ειδικευμένα%';
UPDATE directory_companies SET activity_description = 'Wholesale of other office machinery and equipment' WHERE activity_description LIKE 'Χονδρικό εμπόριο άλλων μηχανών και εξοπλισμού γραφείου';
UPDATE directory_companies SET activity_description = 'Wholesale of waste and scrap' WHERE activity_description LIKE 'Χονδρικό εμπόριο απορριμμάτων%';
UPDATE directory_companies SET activity_description = 'Wholesale of perfume and cosmetics' WHERE activity_description LIKE 'Χονδρικό εμπόριο αρωμάτων και καλλυντικών';
-- Catch any remaining Greek entries with a broader pattern
UPDATE directory_companies SET activity_description = 'Wholesale of sugar, chocolate and sugar confectionery' WHERE activity_description LIKE 'Χονδρικό εμπόριο ζάχαρης%';
UPDATE directory_companies SET activity_description = 'Wholesale of other household goods' WHERE activity_description LIKE 'Χονδρικό εμπόριο κεραμικών%';
UPDATE directory_companies SET activity_description = 'Wholesale of flowers and plants' WHERE activity_description LIKE 'Χονδρικό εμπόριο λουλουδιών%';
UPDATE directory_companies SET activity_description = 'Non-specialised wholesale trade' WHERE activity_description LIKE 'Χονδρικό εμπόριο μη εξειδικευμένο%';